### ISSUE TITLE
platformBroswerDynamic Error on Compile

### ISSUE THREAD

**Issue by markjmuellerjr** [treehouse-projects/photoblog#2]
When I run: `npm  run serve`

I get the following error in my console and compiling fails:
```
ERROR in [at-loader] src/main.ts:3:10
  Module '"/Users/markmueller/Development/photo_blog/node_modules/@angular/platform-browser-dynamic/index"' has no exported member 'platormBrowserDynamic'.
```

I've updated my packages.json file, uninstalled the node_modules folder and tried `npm install --update-binary` & `npm install --build-from-source` with and without `sudo`.

**Comment by chalkers** [comment]
Hi there

I believe you misspelled `platformBrowserDynamic` - you missed the `f` in platform. :)

Hope that helps!

Regards,   
Andrew
